FROM alpine:3.7
RUN apk update
RUN apk add curl wget
RUN apk --update add supervisor && mkdir /etc/supervisor.d/
RUN cd /tmp
RUN wget --no-check-certificate https://releases.hashicorp.com/consul-template/0.19.4/consul-template_0.19.4_linux_amd64.zip
RUN unzip consul-template_0.19.4_linux_amd64.zip
RUN mv consul-template /usr/bin/
RUN rm consul-template_0.19.4_linux_amd64.zip
ADD vault_init.sh .
RUN chmod 755 vault_init.sh

RUN adduser supervisorduser -D

ADD vault-consul-template.ini /etc/supervisor.d/
RUN chown -R supervisorduser:supervisorduser /etc/supervisor.d/

ADD supervisord.conf /tmp/supervisord.conf
RUN chown supervisorduser:supervisorduser /tmp/supervisord.conf
RUN chmod 644 /tmp/supervisord.conf

CMD tail -f /dev/null
#CMD /usr/bin/supervisord -u supervisorduser -n -c /tmp/supervisord.conf -l /tmp/supervisord.log -j /tmp/supervisord.pid


